language: go
sudo: required
go: 
  - 1.x


install:
- wget https://releases.hashicorp.com/terraform/0.11.5/terraform_0.11.5_linux_amd64.zip
- unzip terraform_0.11.5_linux_amd64.zip
- sudo mv terraform /usr/local/bin
- sudo apt-get update && sudo apt-get install jq


script:
- go build ./
- zip main.zip pager
- cd teraform
- terraform init
- terraform plan -o plan

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then teraform apply plan; fi

