language: go
sudo: required
go: 
  - 1.x


install:
- wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
- sudo unzip terraform_0.11.7_linux_amd64.zip -d /usr/local/bin

script:
- go build ./
- zip main.zip pager
- cd terraform
- terraform init
- terraform plan -out plan

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then terraform apply plan; fi

